---
# These tasks install Zookeeper and Kafka

- name: "Create a directory if it does not exist"
  file:
    path: "{{ kafka_location }}"
    state: "directory"

- name: "Download Kafka files into {{ kafka_location }}"
  get_url:
    url: "{{ kafka_sources_url }}"
    dest: "{{ kafka_location }}"

- name: "Extract {{ kafka_package }} into {{ kafka_location }}"
  unarchive:
    src: "{{ kafka_location }}/{{ kafka_package }}"
    dest:  "{{ kafka_location }}"
    remote_src: "yes"
    extra_opts: ["--strip-components=1"]

- name: "Remove kafka tar file"
  file:
    path: "{{ kafka_location }}/{{ kafka_package }}"
    state: "absent"

- name: "Add zookeeper service file"
  template:
    src: "zookeeper.service.j2"
    dest: "/etc/systemd/system/zookeeper.service"

- name: "Add kafka service file"
  template:
    src: "kafka.service.j2"
    dest: "/etc/systemd/system/kafka.service"

- name: "Enable zookeeper service"
  shell: "systemctl enable zookeeper.service"

- name: "Enable kafka service"
  shell: "systemctl enable kafka.service"

